version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ~/.docker/config.json
        target: /config.json
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
    command: --interval 5

  website:
    image: localhost:5000/miska_website:latest
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    build: 
      context: ./website/
    env_file:
      - website/.env
    volumes:
      - ./website/src/:/usr/src/miska/website/src/
      - ./website/server/:/usr/src/miska/website/server/
      - ./website/pages/:/usr/src/miska/website/pages/
      - ./website/public/:/usr/src/miska/website/public/
      - ./database/content/:/usr/src/miska/database/content/
    ports:
      - 6969:6969
    depends_on:
      - db

  db:
    restart: always
    image: mongo:latest
    volumes:
      - ./database/mongodb/:/data/db/
    env_file:
      - ./database/.env
    ports:
      - 27017:27017
