services:
  website:
    image: localhost:5000/miska_website:latest
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    env_file:
      - website/.env
    volumes:
      - ./database/content/:/usr/src/miska/database/content/
    ports:
      - 6969:6969
    depends_on:
      - db

  db:
    restart: always
    image: mongo:latest
    volumes:
      - ./database/mongodb/:/data/db/
    env_file:
      - ./database/.env
    ports:
      - 27017:27017
