---
resources:
- name: miska
  type: git
  icon: github
  source: 
    uri: https://github.com/SamuelPoulin/miska
    branch: master

- name: miska-website
  type: registry-image
  icon: docker
  source:
    repository: localhost:5000/miska_website
    username: ((registryUser))
    password: ((registryPass))
    skip_ssl_verification: true

jobs:
- name: read-the-readme
  plan:
  - get: miska
    trigger: true
  - task: cat-readme
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: miska
      run:
        path: cat
        args: ["miska/readme.md"]

- name: build-and-push
  plan:
  - get: miska
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: miska
      outputs:
      - name: image
      params:
        CONTEXT: miska/website
      run:
        path: build
  - put: miska-website
    params:
      image: image/image.tar